include(FetchContent)

include(cmake/NotMaintained/tinyxml2.cmake)
include(cmake/NotMaintained/glad.cmake)
include(cmake/NotMaintained/glfw.cmake)
include(cmake/NotMaintained/curl.cmake)
include(cmake/NotMaintained/alphanum.cmake)
include(cmake/NotMaintained/libgit2.cmake)
#include(cmake/NotMaintained/json.cmake)
#include(cmake/NotMaintained/sqlite3.cmake)
#include(cmake/NotMaintained/fmt.cmake)
