name: Linux

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'doc/**'
    - 'bin/**'
    - 'samples/**'
    - '.github/**'
    - 'tests/**'
    - 'README.md'
    - 'LICENSE'

jobs:
  build_Linux_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libasound2-dev libomp-dev
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
