name: Osx

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'doc/**'
    - 'bin/**'
    - 'samples/**'
    - '.github/**'
    - 'tests/**'
    - 'README.md'
    - 'LICENSE'

jobs:
  build_Osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : brew update
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
